# Generated by Django 4.0.5 on 2022-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='symboling',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='wheelbase',
            field=models.FloatField(blank=True),
        ),
    ]
