# Generated by Django 4.0.5 on 2022-06-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_carmodel_symboling_alter_carmodel_wheelbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='wheelbase',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
