# Generated by Django 4.0.5 on 2022-06-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_carmodel_wheelbase_carmodel_bootspacelt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='bootspacelt',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
