# Generated by Django 4.0.5 on 2022-06-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_carmodel_bootspacelt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='bootspacelt',
            new_name='bootSpacelt',
        ),
    ]
