# Generated by Django 4.0.5 on 2022-06-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_bootspacelt_carmodel_bootspacelt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
